name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Apktool
        run: |
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar

      - name: Compile APK
        run: java -jar apktool.jar b Instagram -o Instagram-compiled.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Instagram-compiled
          path: Instagram-compiled.apk