name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install apktool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /usr/local/bin/apktool
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O /usr/local/bin/apktool.jar
          chmod +x /usr/local/bin/apktool

      - name: Compile APK
        run: apktool b Instagram -o Instagram-compiled.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Instagram-compiled
          path: Instagram-compiled.apk